### ISSUE TITLE
Avoid buggy `tests/bootstrap.php` file

### ISSUE THREAD

**Issue by schlessera** [Yoast/whip#13]
The unit tests are bootstrapped through a `tests/bootstrap.php` file.

Apart from the fact that this might break under certain circumstances (that file might actually not yet exist or be stored in a different location, when Composer was used at a different level), this is also not the recommended approach.

With the current form, that bootstrap file is not needed at all if the provided PHPUnit is used to run the tests (`vendor/bin/phpunit`).

If there would be additional autoloading needs for the development environment only (for example, additional classes to load as fixtures for the tests), this would go into an `"autoload-dev"` section in the `composer.json` file.

**Comment by atimmer** [comment]
I tried removing this but then everything exploded for PHP5.2 on Travis. Then I went through a lot of iterations (#18) to finally fix this the following way:
* Only load the autoload file if it exists. The risk is that we have two autoloaders that load the same thing.
* Let the facade check if it already exists before loading.
* Use the built-in PHPUnit on Travis for PHP5.2, for all other PHP versions use the PHPUnit in the vendor folder.
