### ISSUE TITLE
It is possible to tag a new version?

### ISSUE THREAD

**Issue by neurotools** [Yoast/whip#135]
Last tagged version (1.20) is from July 20, 2021. Some important fixes has been added to the package. Most importantly some fixes for warnings on PHP 8.2 because of the use of dynamic properties. Those where fixed on https://github.com/Yoast/whip/commit/022695cf6b0db3a9d9838a80e2f341e8d62e7231 but are not being tagged on a new version, so other packages that has Whip as a dependency have inherited the warnings until there's a new tagged version.

**Comment by joostdekeijzer** [comment]
Yes please!

WordPress recommends PHPv82, see https://wordpress.org/news/2023/10/wordpress-6-4s-php-compatibility/ 

A 3rd party plugin uses Whip and can't update their dependencies. Now I have deprecated errors in my log :(

**Comment by neurotools** [comment]
It's something blocking this? Can I help with that?

**Comment by enricobattocchi** [comment]
Hello @neurotools @joostdekeijzer, we just released [version 2.0.0](https://github.com/Yoast/whip/releases/tag/2.0.0) which supports up to PHP 8.3.
Please note that we moved to namespaces instead of prefixes so you'll have to adapt your code accordingly!
