### ISSUE TITLE
Class `Whip_PHPVersionDetector` should be final or avoid `self`

### ISSUE THREAD

**Issue by schlessera** [Yoast/whip#3]
The class `Whip_PHPVersionDetector` is not `final` and has its properties be set to `protected`.

However, it uses constants and refers to them using `self::`. This will very probably lead to bugs, because an extending class will not only need to override the constants, but also all the methods referencing it, or else the extending class will refer to the constants in the parent class.

The proper way to use these constants is to use late static binding (`static::CONST`), but that needs PHP 5.3. 

So, I suggest either:

1. Make that class `final` and have custom classes simply implement the interface instead; or
2. Remove the constants, and have this information be directly returned by methods, which circumvents the late static binding issue.

**Comment by atimmer** [comment]
Since #18, the only locations where self is present are in static functions.
