### ISSUE TITLE
Prevent duplicated notices

### ISSUE THREAD

**Issue by sciamannikoo** [Yoast/whip#36]
Scenario:

- WPSEO
- Another plugin using WHIP with the same requirements

When the requirements are not met, the notice is shown twice.

This is because, for every time `whip_wp_check_versions` is called (and requirements are not met), `\Whip_WPMessagePresenter::register_hooks` is also called.

This creates as many hooks to `admin_notices` as many calls to `whip_wp_check_versions` there are.

I think the problem is that `whip_wp_check_versions` creates a new instance of `Whip_WPMessagePresenter` every time is called.

Something like that may prevent duplicate notices:
```php
function whip_wp_check_versions( $requirements ) {
	//...

	global $whip_message_presenter;
	if ( ! isset( $whip_message_presenter ) ) {
		$mostRecentMessage      = $checker->getMostRecentMessage();
		$whip_message_presenter = new Whip_WPMessagePresenter( $mostRecentMessage );
		$whip_message_presenter->register_hooks();
	}
}
```

But I'm not sure if that's the best approach.

**Comment by atimmer** [comment]
I think its better to check in https://github.com/Yoast/whip/blob/master/src/presenters/Whip_WPMessagePresenter.php#L23 for a global whether or not `admin_notices` has been hooked or not.

This way people using the longer version are also protected against duplicated messages.

**Comment by atimmer** [comment]
Anyway, would you be able to PR this?

**Comment by sciamannikoo** [comment]
@atimmer yes, I would.

I thought about dealing with globals there, but as I'm not a big fan of globals, I was trying to use it as early as possible :)

No problem anyway: I'll send a PR based on your suggestion.

**Comment by DrewAPicture** [comment]
Couldn't you avoid the global altogether by simply firing `register_hooks()` on a custom action (meta, I know), and then checking `has_action()`? i.e.

```php
if ( ! has_action( 'whip_register_hooks' ) ) {
    add_action( 'whip_register_hooks', array( $presenter, 'register_hooks' ) );
}

do_action( 'whip_register_hooks', $presenter );
```

**Comment by atimmer** [comment]
That is very elegant. I'll create a new issue for it.
