### ISSUE TITLE
We can avoid a global by using filters to prevent duplicate messages

### ISSUE THREAD

**Issue by atimmer** [Yoast/whip#40]
See https://github.com/Yoast/whip/issues/36#issuecomment-316867870

**Comment by DrewAPicture** [comment]
@atimmer I can prepare a PR if you like.

**Comment by atimmer** [comment]
@DrewAPicture That would be nice 😁

**Comment by DrewAPicture** [comment]
PR: #44

**Comment by DrewAPicture** [comment]
I think this can be closed?
